Created the plotfasta function and loadkmers function
JokingHero/NanoporeMultiEventalign.jl pull request #3
Opened 2021-03-14 19:59 UTC by Thohil

Created a function to plot fasta data using the kmers
Lazar created a function to load in kmers from the .model file

2021-03-15 09:41 UTC, JokingHero requested changes

2021-03-15 09:41 UTC, JokingHero commented on Project.toml
> +PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
PyPlot not needed

2021-03-15 09:41 UTC, JokingHero commented on src/NanoporeMultiEventalign.jl
> +include("utils.jl")
this should be at the top

2021-03-15 09:41 UTC, JokingHero commented on src/NanoporeMultiEventalign.jl
> +#plotdata("test/sample_data/reference.fa")
should not be here

2021-03-15 09:41 UTC, JokingHero commented on src/persistence.jl
> +# Access syntax: kmers["GCTGT"][2] gets stdvt of the kmer
you can put this into documentation with 

"

"

2021-03-15 09:41 UTC, JokingHero commented on src/persistence.jl
> +    model_path = "models/r9.4_70bps.u_to_t_rna.5mer.template.model"
should be parameter with default

2021-03-15 09:41 UTC, JokingHero commented on src/utils.jl
> +    dataString = convert(String, data[1])
keep the naming conventions consistent with julia style

2021-03-15 09:41 UTC, JokingHero commented on src/utils.jl
> +    for i in 1:(length(dataString)-4)
assumes the size of the kmer

2021-03-15 09:41 UTC, JokingHero commented on src/utils.jl
> +        push!(plotList,parse(Float64,kmers[kmerKey][1]))
keep spaces etc

2021-03-15 09:41 UTC, JokingHero commented on src/utils.jl
> +    png("plot")#saves the plot as a png named plot
plot path should be input

2021-03-15 09:41 UTC, JokingHero commented on src/utils.jl
> +function plotdata(path::String)
instead make funciton that processes fasta into kmer mean points

2021-03-17 13:02 UTC, JokingHero commented on src/NanoporeMultiEventalign.jl
> +export loadnanoporefast5, loadfasta, loadkmers, fasta_to_kmer_valus
should be values?
fasta_to_model maybe? 

After you fix this try merging this branch to the main, fix conflicts beforehand.

2021-03-17 13:03 UTC, JokingHero approved these changes
Adress my comment and merge this to the main.

2021-03-17 14:52 UTC, Thohil commented
It says "Only those with write access to this repository can merge pull requests." so i am not sure if i have permission to merge the changes into main
![image](https://user-images.githubusercontent.com/51682076/111487374-97d26b00-8738-11eb-97de-3ae129bd586d.png)

2021-03-17 15:25 UTC, JokingHero commented
You have not accepted the invitation to be the contributor, its waiting for some time now.

2021-03-17 15:42 UTC, Thohil commented
I found the invitation, however github invitations expire after 7 days so i can't use it. is it possible for you to resend the invitation?

2021-03-17 16:36 UTC, merged