dtw algorithm
JokingHero/NanoporeMultiEventalign.jl pull request #4
Opened 2021-03-25 19:33 UTC by Thohil

this is using the dtw algorithm from https://github.com/baggepinnen/DynamicAxisWarping.jl

unknown.png is gotten from running matchplot(a,b,ds=100,separation=1) where a and b where 2 sets of fast 5 data

image.png is gotten from running c, d = dtw_stretched(a,b) then running plot([c d])

2021-03-25 20:38 UTC, JokingHero requested changes

2021-03-25 20:38 UTC, JokingHero commented on Project.toml
> +Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distances added to deps but nowhere imported

2021-03-25 20:38 UTC, JokingHero commented on src/NanoporeMultiEventalign.jl
> +export dtw_test
dtw_test was just a function I added to make you hello world, you can remove it entirely

2021-03-25 20:38 UTC, JokingHero commented on src/dtw.jl
> +"
don't understand what is this function supposed to do. What I think it does now:
1. take arbitrary data1, data2 (which can literally be anything as types are not defined)
2. run dtw from DynamicAxisWarping package
3. Iterate over the results and push them into another vector? why is it needed at all? It is fine to keep the same interface/output as DynamicAxisWarping package 

What I think this function should be doing:
1. Named nanopore_dtw(x::Vector{Float32}, y::Vector{Float32})
2. Does the fast5 read segmentation on both x, and y 
3. runs dtw on x, y with Bhattacharyya distance from Distances package
4. Returns dtw output - same as in dtw function

You can implement some simple read segmentation with change point analysis packages e.g. https://github.com/STOR-i/Changepoints.jl
Sensitivity should be a parameter, I guess you can set it to some average standard deviation from our model kmer values.

Detect change points -> this gives the set of points for each change point -> for each set of points you can calculate mean + standard deviation -> use these to calculate distance between two normal distributions https://en.wikipedia.org/wiki/Bhattacharyya_distance you can use Bhattacharyya distance
from Distances package

2021-03-25 20:39 UTC, JokingHero commented on src/dtw.jl
> +"
Also, add a test for that function on some small random data, this will allow us to detect changes when they happen in our dependencies.

2021-03-25 20:40 UTC, JokingHero commented on src/dtw.jl
> +"
And there is no value by having plot added to the library, just remove that file

2021-04-19 08:05 UTC, JokingHero commented on src/NanoporeMultiEventalign.jl
> +export kmerDist, Bhattacharyya
small lettern names for funcitons

2021-04-19 08:11 UTC, JokingHero commented on src/dtw.jl
> +    if filterkernel !== nothing
remove it

2021-05-02 21:17 UTC, Thohil commented
I added the plot function for the alignment, and made the resulting plot a bit higher resolution as you asked.
however i am having a bit of a problem understanding how i am supposed to increase the penalty for horizontal alignments in the dtw algorithm.

    for c = 2:n
        for r = 2:m
            best_neighbor_cost = min(D[r-1, c], D[r-1, c-1], D[r, c-1])
            D[r, c] += best_neighbor_cost
        end
    end

should i multiply the best_neighbor_cost by a variable that is dependent on the difference between c and r here? or would that be wrong?

2021-05-03 15:14 UTC, JokingHero approved these changes

2021-05-03 15:14 UTC, JokingHero commented on test/runtests.jl
> +        #@test dtw(true)
add some tests

2021-05-03 15:14 UTC, JokingHero commented on test/runtests.jl
> +        @test Bhattacharyya(kmerDist(1,2),kmerDist(3,2)) == 0.029445758914095864
check this in some other language, or other results

2021-05-03 15:14 UTC, JokingHero commented on src/utils.jl
> +    [Bhattacharyya(s1[j], s2[i]) for i in 1:length(s2), j in 1:length(s1)]
return

2021-05-03 15:14 UTC, JokingHero commented on src/dtw.jl
> +    r, c       = size(D)
just format the code

2021-05-03 15:14 UTC, JokingHero commented on test/runtests.jl
> +end
add a plot

2021-05-03 15:14 UTC, JokingHero commented on test/runtests.jl
> +        #@test dtw(true)
dont need to test the plot

2021-05-03 15:14 UTC, JokingHero commented on test/runtests.jl
> +end
plot should be distributions, connected by lines

2021-05-03 15:15 UTC, merged